### ISSUE TITLE
Text to fix

### ISSUE THREAD

**Issue by OxyFlax** [gigimai/SWTitan#14]
"Hi, I'm Jarvis. What movie would you like to see?"

Captain America -> "Great choice, 5 stars reviews on IMDB, you'll love it :)"
"When do you want to see it?"

Tomorrow after 8pm -> "Which district?"

District 1 or 3 please -> "Alright, this is what I've got"

**Comment by gigimai** [comment]
Fix the issue with text input could not be selected on the first tap as well

**Comment by OxyFlax** [comment]
Fix App name : jarvis (not Jarvis)

**Comment by gigimai** [comment]
What's wrong with Jarvis? Most of the app have Capitalized name, tell me the rationale of this

**Comment by OxyFlax** [comment]
jarvis is so strong that it doesn't need a capital letter :D (Florent's idea)
